# Generated by Django 5.1.7 on 2025-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.CharField(blank=True, help_text='Ex: React, Django, Python', max_length=255),
        ),
    ]
