# Generated by Django 5.1.7 on 2025-04-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_publication', models.DateField()),
                ('date_limite', models.DateField()),
                ('postes_disponibles', models.IntegerField()),
                ('lien', models.URLField()),
                ('secteur', models.CharField(max_length=200)),
                ('fonction', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=100)),
                ('niveau_etudes', models.CharField(max_length=50)),
                ('contrat', models.CharField(max_length=50)),
                ('teletravail', models.CharField(max_length=50)),
            ],
        ),
    ]
