# Generated by Django 5.1.7 on 2025-04-10 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='favorites_f_user_id_645357_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['job'], name='favorites_f_job_id_85dde0_idx'),
        ),
    ]
