# Generated by Django 5.1.7 on 2025-04-14 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_favorite_options_and_more'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='favorite',
            name='favorites_f_user_id_645357_idx',
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='favorites_f_job_id_85dde0_idx',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
